name: CI Release

on:
  workflow_call:
    inputs:
      TAG:
        description: 'Semantic version tag'
        required: true
        type: string
    outputs:
      TAG:
        description: 'Tag used for release'
        value: ${{ jobs.set-tag.outputs.TAG }}

jobs:
  set-tag:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.set-tag.outputs.TAG }}
    steps:
      - name: Set tag
        id: set-tag
        run: |
          echo "TAG=${{ inputs.TAG }}" >> $GITHUB_ENV
          echo "TAG=${{ inputs.TAG }}" >> $GITHUB_OUTPUT
